#!/usr/bin/env python3
"""Produce a self-contained single-file diag script.

Reads `diag/<NN>_<name>.py`, inlines every `ocdiag/*.py` submodule into a
runtime bootstrap (registering them in `sys.modules` before the original
`from ocdiag import ...` statements run), and writes the result to stdout.

Usage:
    python3 lib/bundle.py gateway > standalone-gateway.py
    python3 lib/bundle.py 04_gateway > standalone-gateway.py

The bundled script needs only Python 3.8+; no openclaw-diag-cli checkout.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent

# Single source of truth: ocdiag.dispatcher. We import it dynamically so the
# bundle script stays runnable from a fresh checkout (no install needed).
sys.path.insert(0, str(REPO_ROOT))
from ocdiag.dispatcher import STATE_COLLECTORS  # noqa: E402

MODULES: List[tuple] = [(mid, rel) for mid, _label, rel in STATE_COLLECTORS]
MODULE_BY_ID = {mid: rel for mid, rel in MODULES}

# Order matters: each submodule is exec'd into its own module object, and its
# `from . import X` / `from ocdiag.X import Y` statements run during exec —
# so dependencies must already be in sys.modules.
OCDIAG_SUBMODULE_ORDER = [
    "paths",
    "sensitive",
    "timeutil",
    "tokens",
    "jsonlog",
    "output",
    "recent_logs",
    "cli",       # imports `from . import paths`
]


def resolve_script(arg: str) -> Path:
    if arg in MODULE_BY_ID:
        return REPO_ROOT / MODULE_BY_ID[arg]
    candidate = REPO_ROOT / "diag" / arg
    if candidate.is_file():
        return candidate
    candidate_py = REPO_ROOT / "diag" / f"{arg}.py"
    if candidate_py.is_file():
        return candidate_py
    raise SystemExit(
        f"Error: unknown module id or script: {arg!r}. "
        f"Use one of: {', '.join(mid for mid, _ in MODULES)}"
    )


def split_header(source: str) -> tuple:
    """Split a script into (shebang, docstring, body).

    Recognises a single-line `#!/...` shebang and the first triple-quoted
    docstring. Anything else becomes body.
    """
    lines = source.split("\n")
    i = 0
    shebang = ""
    if i < len(lines) and lines[i].startswith("#!"):
        shebang = lines[i]
        i += 1
    # Skip blank lines / comments before docstring
    while i < len(lines) and (lines[i].strip() == "" or lines[i].lstrip().startswith("#")):
        i += 1
    docstring_lines: List[str] = []
    if i < len(lines) and (lines[i].lstrip().startswith('"""') or lines[i].lstrip().startswith("'''")):
        quote = '"""' if '"""' in lines[i] else "'''"
        first = lines[i]
        docstring_lines.append(first)
        # Single-line docstring?
        if first.count(quote) >= 2:
            i += 1
        else:
            i += 1
            while i < len(lines):
                docstring_lines.append(lines[i])
                if quote in lines[i]:
                    i += 1
                    break
                i += 1
    body = "\n".join(lines[i:])
    docstring = "\n".join(docstring_lines)
    return shebang, docstring, body


def strip_path_hack(body: str) -> str:
    """Remove the `sys.path.insert(0, ...parent.parent)` line; the bundle
    no longer needs to point at a checkout to find the `ocdiag` package."""
    pattern = re.compile(
        r"^sys\.path\.insert\(\s*0\s*,\s*str\(\s*Path\(__file__\)\.resolve\(\)\.parent\.parent\s*\)\s*\)\s*\n",
        re.MULTILINE,
    )
    return pattern.sub("", body)


def extract_future_imports(body: str) -> tuple:
    """Pull `from __future__ import ...` lines out of the body so we can put
    them at the top of the bundled file (Python requires this)."""
    pattern = re.compile(r"^from\s+__future__\s+import[^\n]*\n", re.MULTILINE)
    futures = pattern.findall(body)
    body_without = pattern.sub("", body)
    return "".join(futures), body_without


def read_ocdiag_sources() -> Dict[str, str]:
    """Read ocdiag/__init__.py and the submodule files we know we need."""
    out: Dict[str, str] = {}
    out["ocdiag"] = (REPO_ROOT / "ocdiag" / "__init__.py").read_text(encoding="utf-8")
    for name in OCDIAG_SUBMODULE_ORDER:
        out[f"ocdiag.{name}"] = (REPO_ROOT / "ocdiag" / f"{name}.py").read_text(encoding="utf-8")
    return out


def render_bootstrap(sources: Dict[str, str]) -> str:
    """Render the runtime bootstrap that registers ocdiag modules."""
    # Use repr() for embedding; Python repr of strings round-trips reliably.
    parts = ["# ── Inlined ocdiag bootstrap (generated by lib/bundle.py) ──",
             "import sys as _sys",
             "import types as _types",
             "_OCDIAG_SOURCES = {"]
    parts.append(f"    'ocdiag': {sources['ocdiag']!r},")
    for name in OCDIAG_SUBMODULE_ORDER:
        full = f"ocdiag.{name}"
        parts.append(f"    {full!r}: {sources[full]!r},")
    parts.append("}")
    parts.append("")
    parts.append("def _ocdiag_bootstrap():")
    parts.append("    if 'ocdiag' in _sys.modules:")
    parts.append("        return")
    parts.append("    pkg = _types.ModuleType('ocdiag')")
    parts.append("    pkg.__path__ = []")
    parts.append("    pkg.__package__ = 'ocdiag'")
    parts.append("    _sys.modules['ocdiag'] = pkg")
    parts.append("    exec(compile(_OCDIAG_SOURCES['ocdiag'], '<ocdiag/__init__.py>', 'exec'), pkg.__dict__)")
    parts.append(f"    for _name in {OCDIAG_SUBMODULE_ORDER!r}:")
    parts.append("        full = 'ocdiag.' + _name")
    parts.append("        m = _types.ModuleType(full)")
    parts.append("        m.__package__ = 'ocdiag'")
    parts.append("        _sys.modules[full] = m")
    parts.append("        setattr(pkg, _name, m)")
    parts.append("        exec(compile(_OCDIAG_SOURCES[full], '<' + full + '>', 'exec'), m.__dict__)")
    parts.append("")
    parts.append("_ocdiag_bootstrap()")
    parts.append("del _ocdiag_bootstrap")
    parts.append("# ── End inlined ocdiag ──")
    return "\n".join(parts)


def build_bundle(script_path: Path) -> str:
    source = script_path.read_text(encoding="utf-8")
    shebang, docstring, body = split_header(source)
    if not shebang:
        shebang = "#!/usr/bin/env python3"
    body = strip_path_hack(body)
    futures, body = extract_future_imports(body)
    sources = read_ocdiag_sources()
    bootstrap = render_bootstrap(sources)
    header_comment = (
        f"# Self-contained bundle of {script_path.relative_to(REPO_ROOT)} "
        "(generated by openclaw-diag-cli/lib/bundle.py).\n"
        "# Requires only Python 3.8+ stdlib. No openclaw-diag-cli checkout needed.\n"
    )
    chunks = [shebang]
    if docstring:
        chunks.append(docstring)
    if futures:
        chunks.append(futures.rstrip("\n"))
    chunks.append(header_comment.rstrip("\n"))
    chunks.append(bootstrap)
    chunks.append(body.lstrip("\n"))
    return "\n".join(chunks)


def main(argv: Optional[List[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help"):
        sys.stdout.write(__doc__ or "")
        return 0
    script_path = resolve_script(argv[0])
    sys.stdout.write(build_bundle(script_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
